# Generated by Django 4.2.4 on 2023-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('tipo_cliente', models.IntegerField(max_length=1)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_por_hoja', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('neto_por_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
